name: kidsdo
description: Aplicación de recompensas para niños
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_app_check: ^0.3.2+5
  google_sign_in: ^6.3.0

  
  
  # State Management & Routing
  get: ^4.6.5
  
  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  image_picker: ^1.0.2
  path_provider: ^2.1.0
  
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  lottie: ^2.6.0
  google_fonts: ^5.1.0
  shimmer: ^3.0.0
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300